// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-2VSmvUZxkm4eIL6Vbm41RPPbJUS2zo',
    appId: '1:12345678901:web:abcdef1234567890',
    messagingSenderId: '12345678901',
    projectId: 'misy-app-2fb01',
    authDomain: 'misy-app-2fb01.firebaseapp.com',
    storageBucket: 'misy-app-2fb01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-2VSmvUZxkm4eIL6Vbm41RPPbJUS2zo',
    appId: '1:12345678901:android:abcdef1234567890',
    messagingSenderId: '12345678901',
    projectId: 'misy-app-2fb01',
    storageBucket: 'misy-app-2fb01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-2VSmvUZxkm4eIL6Vbm41RPPbJUS2zo',
    appId: '1:12345678901:ios:abcdef1234567890',
    messagingSenderId: '12345678901',
    projectId: 'misy-app-2fb01',
    storageBucket: 'misy-app-2fb01.appspot.com',
    iosBundleId: 'com.misy.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-2VSmvUZxkm4eIL6Vbm41RPPbJUS2zo',
    appId: '1:12345678901:macos:abcdef1234567890',
    messagingSenderId: '12345678901',
    projectId: 'misy-app-2fb01',
    storageBucket: 'misy-app-2fb01.appspot.com',
    iosBundleId: 'com.misy.rider',
  );
}