// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUQs8toDM2r8ph0WujvpyNkj_qVIKnSY',
    appId: '1:1062917624003:web:c3608b3692e7c225bd9276',
    messagingSenderId: '1062917624003',
    projectId: 'misy-95336',
    authDomain: 'misy-95336.firebaseapp.com',
    storageBucket: 'misy-95336.appspot.com',
    measurementId: 'G-ZP0RPLRRBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNUQs8toDM2r8ph0WujvpyNkj_qVIKnSY',
    appId: '1:1062917624003:android:536998923c207f30bd9276',
    messagingSenderId: '1062917624003',
    projectId: 'misy-95336',
    storageBucket: 'misy-95336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNUQs8toDM2r8ph0WujvpyNkj_qVIKnSY',
    appId: '1:1062917624003:ios:bd9276c3608b3692',
    messagingSenderId: '1062917624003',
    projectId: 'misy-95336',
    storageBucket: 'misy-95336.appspot.com',
    iosBundleId: 'com.misy.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNUQs8toDM2r8ph0WujvpyNkj_qVIKnSY',
    appId: '1:1062917624003:macos:bd9276c3608b3692',
    messagingSenderId: '1062917624003',
    projectId: 'misy-95336',
    storageBucket: 'misy-95336.appspot.com',
    iosBundleId: 'com.misy.rider',
  );
}
